export const sampleGarmentData = [
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
  {
    name: 'Fashionable Blue Dress',
    garment_id: 'G5e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Dresses',
    brand: 'Van Heusen Australia',
    main_colour: 'Blue',
    season: 'Spring/Summer',
    collection_year: '2019',
    image: 'https://picsum.photos/200',
    style: 'Feminine',
    colors: ['Blue'],
    size: '32',
    fabric: ['Cotton'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '43.00',
    currency: 'EUR',
  },
  {
    name: 'Cirque du Soleil',
    garment_id: 'G1e29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Jacket',
    brand: 'Zara',
    main_colour: 'Red',
    season: 'Fall/Winter',
    collection_year: '2010',
    image: 'https://picsum.photos/200',
    style: 'Rocker',
    colors: ['Red', 'Aero White', 'Black'],
    size: 'S',
    fabric: ['Cotton', 'Polyester'],
    gender: 'F',
    purchase_date: '2021/10/08',
    price_of_purchase: '432.10',
    currency: 'GBP',
  },
  {
    name: 'Lorem Ipsum',
    garment_id: 'G2a29f8bd-e7cb-4679-a7ad-c47e563b1ccf',
    garment_type: 'Trousers',
    brand: 'H&M',
    main_colour: 'Blue',
    season: 'Sping/Summer',
    collection_year: '205',
    image: 'https://picsum.photos/200',
    style: 'Streetwear',
    colors: ['Space Blue'],
    size: 'XXL',
    fabric: ['Cotton', 'Denim'],
    gender: 'M',
    purchase_date: '2021/10/08',
    price_of_purchase: '101.10',
    currency: 'USD',
  },
];
